"""Curated-indicator namespaces, grouped by theme.

Generated by tools/gen_curation.py from tools/curation_design.tsv -- do not
edit by hand. Each interior class mirrors one level of an indicator's dotted
path; leaves are :class:`Indicator` objects.
"""

from __future__ import annotations

from functools import cached_property

from ..types import Cycle
from ._indicator import Indicator, IndicatorSpec, _SeriesClient

__all__ = ["_CurationGroups"]


class _Rate:
    """Curated indicators under ``rate``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.base = Indicator(
            client,
            IndicatorSpec(
                path="rate.base",
                name_ko="한국은행 기준금리",
                name_en="Bank of Korea Base Rate",
                stat_code="722Y001",
                cycle=Cycle.DAILY,
                item_code1="0101000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.call = Indicator(
            client,
            IndicatorSpec(
                path="rate.call",
                name_ko="콜금리(익일물)",
                name_en="Call Rate (Overnight)",
                stat_code="817Y002",
                cycle=Cycle.DAILY,
                item_code1="010101000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.koribor_3m = Indicator(
            client,
            IndicatorSpec(
                path="rate.koribor_3m",
                name_ko="KORIBOR(3개월)",
                name_en="KORIBOR(3 month)",
                stat_code="817Y002",
                cycle=Cycle.DAILY,
                item_code1="010150000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.cd_91d = Indicator(
            client,
            IndicatorSpec(
                path="rate.cd_91d",
                name_ko="CD수익률(91일)",
                name_en="CD(91 day)",
                stat_code="817Y002",
                cycle=Cycle.DAILY,
                item_code1="010502000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.msb_364d = Indicator(
            client,
            IndicatorSpec(
                path="rate.msb_364d",
                name_ko="통안증권수익률(364일)",
                name_en="Monetary Stabilization Bonds(364 day)",
                stat_code="817Y002",
                cycle=Cycle.DAILY,
                item_code1="010400001",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.treasury_3y = Indicator(
            client,
            IndicatorSpec(
                path="rate.treasury_3y",
                name_ko="국고채수익률(3년)",
                name_en="Treasury Bonds(3 year)",
                stat_code="817Y002",
                cycle=Cycle.DAILY,
                item_code1="010200000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.treasury_5y = Indicator(
            client,
            IndicatorSpec(
                path="rate.treasury_5y",
                name_ko="국고채수익률(5년)",
                name_en="Treasury Bonds(5 year)",
                stat_code="817Y002",
                cycle=Cycle.DAILY,
                item_code1="010200001",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.corporate_bond_3y = Indicator(
            client,
            IndicatorSpec(
                path="rate.corporate_bond_3y",
                name_ko="회사채수익률(3년,AA-)",
                name_en="Corporate Bonds(3 year, AA-)",
                stat_code="817Y002",
                cycle=Cycle.DAILY,
                item_code1="010300000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.deposit = Indicator(
            client,
            IndicatorSpec(
                path="rate.deposit",
                name_ko="예금은행 수신금리",
                name_en="Interest Rate on Time & Savings Deposits of CBs & SBs",
                stat_code="121Y002",
                cycle=Cycle.MONTHLY,
                item_code1="BEABAA2",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.loan = Indicator(
            client,
            IndicatorSpec(
                path="rate.loan",
                name_ko="예금은행 대출금리",
                name_en="Interest Rate on Loans & Discounts of CBs & SBs",
                stat_code="121Y006",
                cycle=Cycle.MONTHLY,
                item_code1="BECBLA01",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Credit:
    """Curated indicators under ``credit``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.total_deposits = Indicator(
            client,
            IndicatorSpec(
                path="credit.total_deposits",
                name_ko="예금은행총예금(말잔)",
                name_en="Total Deposits of CBs & SBs(Avg.)",
                stat_code="104Y013",
                cycle=Cycle.MONTHLY,
                item_code1="BCB1",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.total_loans = Indicator(
            client,
            IndicatorSpec(
                path="credit.total_loans",
                name_ko="예금은행대출금(말잔)",
                name_en="Loans of CBs & SBs(Avg.)",
                stat_code="104Y016",
                cycle=Cycle.MONTHLY,
                item_code1="BDCA1",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.household_credit = Indicator(
            client,
            IndicatorSpec(
                path="credit.household_credit",
                name_ko="가계신용",
                name_en="Credit to Households",
                stat_code="151Y001",
                cycle=Cycle.QUARTERLY,
                item_code1="1000000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.household_delinquency_rate = Indicator(
            client,
            IndicatorSpec(
                path="credit.household_delinquency_rate",
                name_ko="가계대출연체율",
                name_en="Household Loans Delinquency Rate",
                stat_code="141Y005",
                cycle=Cycle.MONTHLY,
                item_code1="R5AB00",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Money:
    """Curated indicators under ``money``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.m1 = Indicator(
            client,
            IndicatorSpec(
                path="money.m1",
                name_ko="M1(협의통화, 평잔)",
                name_en="M1(Narrow Money, Avg.)",
                stat_code="161Y002",
                cycle=Cycle.MONTHLY,
                item_code1="BBLA00",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.m2 = Indicator(
            client,
            IndicatorSpec(
                path="money.m2",
                name_ko="M2(광의통화, 평잔)",
                name_en="M2(Broad Money, Avg.)",
                stat_code="161Y006",
                cycle=Cycle.MONTHLY,
                item_code1="BBHA00",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.lf = Indicator(
            client,
            IndicatorSpec(
                path="money.lf",
                name_ko="Lf(평잔)",
                name_en="Lf(Avg.)",
                stat_code="171Y004",
                cycle=Cycle.MONTHLY,
                item_code1="LA00000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.l = Indicator(
            client,
            IndicatorSpec(
                path="money.l",
                name_ko="L(말잔)",
                name_en="L(End of)",
                stat_code="172Y002",
                cycle=Cycle.MONTHLY,
                item_code1="X000000",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Fx:
    """Curated indicators under ``fx``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.usd = Indicator(
            client,
            IndicatorSpec(
                path="fx.usd",
                name_ko="원/달러 환율(종가)",
                name_en="KRW/USD(Closing Rate)",
                stat_code="731Y003",
                cycle=Cycle.DAILY,
                item_code1="0000013",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.jpy = Indicator(
            client,
            IndicatorSpec(
                path="fx.jpy",
                name_ko="원/엔(100엔) 환율(매매기준율)",
                name_en="KRW/JPY(100 Yen)",
                stat_code="731Y001",
                cycle=Cycle.DAILY,
                item_code1="0000002",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.eur = Indicator(
            client,
            IndicatorSpec(
                path="fx.eur",
                name_ko="원/유로 환율(매매기준율)",
                name_en="KRW/EURO",
                stat_code="731Y001",
                cycle=Cycle.DAILY,
                item_code1="0000003",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.cny = Indicator(
            client,
            IndicatorSpec(
                path="fx.cny",
                name_ko="원/위안 환율(종가)",
                name_en="KRW/CNY(Closing Rate)",
                stat_code="731Y003",
                cycle=Cycle.DAILY,
                item_code1="0000010",
                item_code2=None,
                item_code3=None,
            ),
        )


class _StockKospi:
    """Curated indicators under ``stock.kospi``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.index = Indicator(
            client,
            IndicatorSpec(
                path="stock.kospi.index",
                name_ko="코스피지수",
                name_en="KOSPI",
                stat_code="802Y001",
                cycle=Cycle.DAILY,
                item_code1="0001000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.trading_value = Indicator(
            client,
            IndicatorSpec(
                path="stock.kospi.trading_value",
                name_ko="주식거래대금(KOSPI)",
                name_en="KOSPI’s Trading Value",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="1060000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.market_cap = Indicator(
            client,
            IndicatorSpec(
                path="stock.kospi.market_cap",
                name_ko="코스피 시가총액",
                name_en="KOSPI Market Capitalization",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="1040000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.volume = Indicator(
            client,
            IndicatorSpec(
                path="stock.kospi.volume",
                name_ko="코스피 거래량",
                name_en="KOSPI Trading Volume",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="1050000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.turnover = Indicator(
            client,
            IndicatorSpec(
                path="stock.kospi.turnover",
                name_ko="코스피 회전율",
                name_en="KOSPI Turnover Ratio",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="1090000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.dividend_yield = Indicator(
            client,
            IndicatorSpec(
                path="stock.kospi.dividend_yield",
                name_ko="코스피 배당수익률",
                name_en="KOSPI Dividend Yield",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="1100000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.per = Indicator(
            client,
            IndicatorSpec(
                path="stock.kospi.per",
                name_ko="코스피 PER",
                name_en="KOSPI PER",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="1110000",
                item_code2=None,
                item_code3=None,
            ),
        )


class _StockKosdaq:
    """Curated indicators under ``stock.kosdaq``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.index = Indicator(
            client,
            IndicatorSpec(
                path="stock.kosdaq.index",
                name_ko="코스닥지수",
                name_en="KOSDAQ Index",
                stat_code="802Y001",
                cycle=Cycle.DAILY,
                item_code1="0089000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.trading_value = Indicator(
            client,
            IndicatorSpec(
                path="stock.kosdaq.trading_value",
                name_ko="주식거래대금(KOSDAQ)",
                name_en="KOSDAQ's Trading Value",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="2060000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.market_cap = Indicator(
            client,
            IndicatorSpec(
                path="stock.kosdaq.market_cap",
                name_ko="코스닥 시가총액",
                name_en="KOSDAQ Market Capitalization",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="2040000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.volume = Indicator(
            client,
            IndicatorSpec(
                path="stock.kosdaq.volume",
                name_ko="코스닥 거래량",
                name_en="KOSDAQ Trading Volume",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="2050000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.turnover = Indicator(
            client,
            IndicatorSpec(
                path="stock.kosdaq.turnover",
                name_ko="코스닥 회전율",
                name_en="KOSDAQ Turnover Ratio",
                stat_code="901Y014",
                cycle=Cycle.MONTHLY,
                item_code1="2110000",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Stock:
    """Curated indicators under ``stock``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.kospi = _StockKospi(client)
        self.kosdaq = _StockKosdaq(client)
        self.investor_deposits = Indicator(
            client,
            IndicatorSpec(
                path="stock.investor_deposits",
                name_ko="투자자예탁금",
                name_en="Investor Deposits",
                stat_code="901Y056",
                cycle=Cycle.MONTHLY,
                item_code1="S23A",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Bond:
    """Curated indicators under ``bond``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.trading_value = Indicator(
            client,
            IndicatorSpec(
                path="bond.trading_value",
                name_ko="채권거래대금",
                name_en="Bonds Trading Value",
                stat_code="901Y015",
                cycle=Cycle.MONTHLY,
                item_code1="1",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.treasury_issuance = Indicator(
            client,
            IndicatorSpec(
                path="bond.treasury_issuance",
                name_ko="국고채발행액",
                name_en="Issued Amount of Treasury Bonds",
                stat_code="191Y001",
                cycle=Cycle.MONTHLY,
                item_code1="0200000",
                item_code2="3",
                item_code3=None,
            ),
        )


class _Growth:
    """Curated indicators under ``growth``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.gdp_growth = Indicator(
            client,
            IndicatorSpec(
                path="growth.gdp_growth",
                name_ko="경제성장률(실질, 계절조정 전기대비)",
                name_en="GDP Growth Rate(S.A.)",
                stat_code="200Y123",
                cycle=Cycle.QUARTERLY,
                item_code1="1117",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.private_consumption_growth = Indicator(
            client,
            IndicatorSpec(
                path="growth.private_consumption_growth",
                name_ko="민간소비증감률(실질, 계절조정 전기대비)",
                name_en="Private Consumption(S.A., % Change)",
                stat_code="200Y102",
                cycle=Cycle.QUARTERLY,
                item_code1="10122",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.facilities_investment_growth = Indicator(
            client,
            IndicatorSpec(
                path="growth.facilities_investment_growth",
                name_ko="설비투자증감률(실질, 계절조정 전기대비)",
                name_en="Facilities Investment(S.A.,% Change)",
                stat_code="200Y102",
                cycle=Cycle.QUARTERLY,
                item_code1="10123",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.construction_investment_growth = Indicator(
            client,
            IndicatorSpec(
                path="growth.construction_investment_growth",
                name_ko="건설투자증감률(실질, 계절조정 전기대비)",
                name_en="Construction Investment(S.A.,% Change)",
                stat_code="200Y102",
                cycle=Cycle.QUARTERLY,
                item_code1="10124",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.exports_growth = Indicator(
            client,
            IndicatorSpec(
                path="growth.exports_growth",
                name_ko="재화의 수출 증감률(실질, 계절조정 전기대비)",
                name_en="Exports of Goods and Services(S.A., % Change)",
                stat_code="200Y102",
                cycle=Cycle.QUARTERLY,
                item_code1="10125",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.gdp_nominal = Indicator(
            client,
            IndicatorSpec(
                path="growth.gdp_nominal",
                name_ko="GDP(명목, 계절조정)",
                name_en="GDP(S.A.,at Current Price)",
                stat_code="200Y107",
                cycle=Cycle.QUARTERLY,
                item_code1="10601",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.gni_per_capita = Indicator(
            client,
            IndicatorSpec(
                path="growth.gni_per_capita",
                name_ko="1인당GNI",
                name_en="Per Capita GNI",
                stat_code="200Y101",
                cycle=Cycle.ANNUAL,
                item_code1="1010601",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.gross_saving_ratio = Indicator(
            client,
            IndicatorSpec(
                path="growth.gross_saving_ratio",
                name_ko="총저축률",
                name_en="Gross Saving Ratio",
                stat_code="200Y102",
                cycle=Cycle.QUARTERLY,
                item_code1="40101",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.gross_investment_ratio = Indicator(
            client,
            IndicatorSpec(
                path="growth.gross_investment_ratio",
                name_ko="국내총투자율",
                name_en="Gross Dom. Investment Ratio",
                stat_code="200Y102",
                cycle=Cycle.QUARTERLY,
                item_code1="40102",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.trade_to_gni_ratio = Indicator(
            client,
            IndicatorSpec(
                path="growth.trade_to_gni_ratio",
                name_ko="수출입의 대 GNI 비율",
                name_en="Ratio of Exports and Imports to GNI",
                stat_code="200Y101",
                cycle=Cycle.ANNUAL,
                item_code1="901",
                item_code2=None,
                item_code3=None,
            ),
        )


class _ProductionManufacturing:
    """Curated indicators under ``production.manufacturing``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.output = Indicator(
            client,
            IndicatorSpec(
                path="production.manufacturing.output",
                name_ko="제조업생산지수",
                name_en="Manufacturing Production Index",
                stat_code="901Y032",
                cycle=Cycle.MONTHLY,
                item_code1="I11AC",
                item_code2="2",
                item_code3=None,
            ),
        )
        self.shipment = Indicator(
            client,
            IndicatorSpec(
                path="production.manufacturing.shipment",
                name_ko="제조업출하지수",
                name_en="Manufacturing Shipment Index",
                stat_code="901Y032",
                cycle=Cycle.MONTHLY,
                item_code1="I11AC",
                item_code2="4",
                item_code3=None,
            ),
        )
        self.inventory = Indicator(
            client,
            IndicatorSpec(
                path="production.manufacturing.inventory",
                name_ko="제조업재고지수",
                name_en="Manufacturing Inventory Index",
                stat_code="901Y032",
                cycle=Cycle.MONTHLY,
                item_code1="I11A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.utilization = Indicator(
            client,
            IndicatorSpec(
                path="production.manufacturing.utilization",
                name_ko="제조업가동률지수",
                name_en="Index of manufacturing capacity utilization rate",
                stat_code="901Y035",
                cycle=Cycle.MONTHLY,
                item_code1="I32A",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Production:
    """Curated indicators under ``production``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.all_industry = Indicator(
            client,
            IndicatorSpec(
                path="production.all_industry",
                name_ko="전산업생산지수",
                name_en="Index of all industry production",
                stat_code="901Y033",
                cycle=Cycle.MONTHLY,
                item_code1="A00",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.manufacturing = _ProductionManufacturing(client)
        self.services = Indicator(
            client,
            IndicatorSpec(
                path="production.services",
                name_ko="서비스업생산지수",
                name_en="index of Services Production",
                stat_code="901Y038",
                cycle=Cycle.MONTHLY,
                item_code1="I51A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.retail_wholesale = Indicator(
            client,
            IndicatorSpec(
                path="production.retail_wholesale",
                name_ko="도소매업생산지수",
                name_en="Wholesale and Retail Production Index",
                stat_code="901Y038",
                cycle=Cycle.MONTHLY,
                item_code1="I51AB",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Consumption:
    """Curated indicators under ``consumption``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.retail_sales = Indicator(
            client,
            IndicatorSpec(
                path="consumption.retail_sales",
                name_ko="소매판매액지수",
                name_en="Retail Sales Index",
                stat_code="901Y100",
                cycle=Cycle.MONTHLY,
                item_code1="G0",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.credit_card_spending = Indicator(
            client,
            IndicatorSpec(
                path="consumption.credit_card_spending",
                name_ko="개인신용카드사용액",
                name_en="Amount of Personal Credit Cards Use",
                stat_code="601Y003",
                cycle=Cycle.MONTHLY,
                item_code1="201000",
                item_code2="00",
                item_code3=None,
            ),
        )
        self.motor_vehicle_sales = Indicator(
            client,
            IndicatorSpec(
                path="consumption.motor_vehicle_sales",
                name_ko="자동차판매액지수",
                name_en="Motor Vehicle Sales Index",
                stat_code="901Y100",
                cycle=Cycle.MONTHLY,
                item_code1="G11",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Investment:
    """Curated indicators under ``investment``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.equipment = Indicator(
            client,
            IndicatorSpec(
                path="investment.equipment",
                name_ko="설비투자지수",
                name_en="Estimated Index of Equipment Investment",
                stat_code="901Y066",
                cycle=Cycle.MONTHLY,
                item_code1="I15B",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.machinery_shipment = Indicator(
            client,
            IndicatorSpec(
                path="investment.machinery_shipment",
                name_ko="설비용 기계류내수출하지수",
                name_en="Domestic Machinery Shipment Index",
                stat_code="901Y036",
                cycle=Cycle.MONTHLY,
                item_code1="20",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.machinery_orders = Indicator(
            client,
            IndicatorSpec(
                path="investment.machinery_orders",
                name_ko="국내기계수주액",
                name_en="Value of Dom. Machinery Orders Received",
                stat_code="901Y018",
                cycle=Cycle.MONTHLY,
                item_code1="I35AAA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.construction_completed = Indicator(
            client,
            IndicatorSpec(
                path="investment.construction_completed",
                name_ko="건설기성액",
                name_en="Value of Construction Completed",
                stat_code="901Y104",
                cycle=Cycle.MONTHLY,
                item_code1="I48A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.building_permits = Indicator(
            client,
            IndicatorSpec(
                path="investment.building_permits",
                name_ko="건축허가면적",
                name_en="Permits Authorized for Bldg. Construction",
                stat_code="901Y037",
                cycle=Cycle.MONTHLY,
                item_code1="I43AA",
                item_code2="1",
                item_code3=None,
            ),
        )
        self.construction_orders = Indicator(
            client,
            IndicatorSpec(
                path="investment.construction_orders",
                name_ko="건설수주액",
                name_en="Value of Construction Orders Received",
                stat_code="901Y020",
                cycle=Cycle.MONTHLY,
                item_code1="I42A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.construction_started = Indicator(
            client,
            IndicatorSpec(
                path="investment.construction_started",
                name_ko="건축착공면적",
                name_en="Results of Construction Start",
                stat_code="901Y103",
                cycle=Cycle.MONTHLY,
                item_code1="1",
                item_code2=None,
                item_code3=None,
            ),
        )


class _BusinessCycle:
    """Curated indicators under ``business_cycle``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.coincident_index = Indicator(
            client,
            IndicatorSpec(
                path="business_cycle.coincident_index",
                name_ko="동행지수순환변동치",
                name_en="Cyclical Component of Coincident Index",
                stat_code="901Y067",
                cycle=Cycle.MONTHLY,
                item_code1="I16D",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.leading_index = Indicator(
            client,
            IndicatorSpec(
                path="business_cycle.leading_index",
                name_ko="선행지수순환변동치",
                name_en="Cyclical Component of Leading Index",
                stat_code="901Y067",
                cycle=Cycle.MONTHLY,
                item_code1="I16E",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Sentiment:
    """Curated indicators under ``sentiment``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.business = Indicator(
            client,
            IndicatorSpec(
                path="sentiment.business",
                name_ko="전산업 기업심리지수실적",
                name_en="Composite Business Sentiment Index",
                stat_code="512Y013",
                cycle=Cycle.MONTHLY,
                item_code1="99988",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.consumer = Indicator(
            client,
            IndicatorSpec(
                path="sentiment.consumer",
                name_ko="소비자심리지수",
                name_en="Composite Consumer Sentiment Index",
                stat_code="511Y002",
                cycle=Cycle.MONTHLY,
                item_code1="FME",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.economic = Indicator(
            client,
            IndicatorSpec(
                path="sentiment.economic",
                name_ko="경제심리지수",
                name_en="Economic Sentiment Index",
                stat_code="513Y001",
                cycle=Cycle.MONTHLY,
                item_code1="E1000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.manufacturing_bsi = Indicator(
            client,
            IndicatorSpec(
                path="sentiment.manufacturing_bsi",
                name_ko="제조업업황실적BSI",
                name_en="BSI(Manufact. Business Con., Tendency)",
                stat_code="512Y013",
                cycle=Cycle.MONTHLY,
                item_code1="C0000",
                item_code2="AA",
                item_code3=None,
            ),
        )


class _CorporateManufacturing:
    """Curated indicators under ``corporate.manufacturing``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.sales_growth = Indicator(
            client,
            IndicatorSpec(
                path="corporate.manufacturing.sales_growth",
                name_ko="제조업매출액증감률",
                name_en="Growth Rate of Sales in Manufacturing",
                stat_code="501Y005",
                cycle=Cycle.ANNUAL,
                item_code1="C231",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.profit_margin = Indicator(
            client,
            IndicatorSpec(
                path="corporate.manufacturing.profit_margin",
                name_ko="제조업매출액세전순이익률",
                name_en="Ordinary Income to Sales in Manufacturing",
                stat_code="501Y006",
                cycle=Cycle.ANNUAL,
                item_code1="C",
                item_code2="A",
                item_code3="6091",
            ),
        )
        self.debt_ratio = Indicator(
            client,
            IndicatorSpec(
                path="corporate.manufacturing.debt_ratio",
                name_ko="제조업부채비율",
                name_en="Debt Ratio in Manufacturing",
                stat_code="501Y007",
                cycle=Cycle.ANNUAL,
                item_code1="C",
                item_code2="A",
                item_code3="707",
            ),
        )


class _Corporate:
    """Curated indicators under ``corporate``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.manufacturing = _CorporateManufacturing(client)


class _Household:
    """Curated indicators under ``household``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.income = Indicator(
            client,
            IndicatorSpec(
                path="household.income",
                name_ko="가구당월평균소득",
                name_en="Monthly Ave. Income of Households",
                stat_code="901Y117",
                cycle=Cycle.QUARTERLY,
                item_code1="1",
                item_code2="I36D",
                item_code3="I36A",
            ),
        )
        self.propensity_to_consume = Indicator(
            client,
            IndicatorSpec(
                path="household.propensity_to_consume",
                name_ko="평균소비성향",
                name_en="Average of Propensity to Consume",
                stat_code="901Y117",
                cycle=Cycle.QUARTERLY,
                item_code1="1",
                item_code2="I36W",
                item_code3="I36A",
            ),
        )
        self.gini = Indicator(
            client,
            IndicatorSpec(
                path="household.gini",
                name_ko="지니계수",
                name_en="Gini's Coefficient",
                stat_code="901Y112",
                cycle=Cycle.ANNUAL,
                item_code1="I38B",
                item_code2="10",
                item_code3=None,
            ),
        )
        self.quintile_ratio = Indicator(
            client,
            IndicatorSpec(
                path="household.quintile_ratio",
                name_ko="5분위배율",
                name_en="Income of Highest Quintile/Income of Lowest Quintile(by quintile, ratio)",
                stat_code="901Y112",
                cycle=Cycle.ANNUAL,
                item_code1="I38B",
                item_code2="20",
                item_code3=None,
            ),
        )


class _Employment:
    """Curated indicators under ``employment``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.unemployment_rate = Indicator(
            client,
            IndicatorSpec(
                path="employment.unemployment_rate",
                name_ko="실업률",
                name_en="Unemployment Rate",
                stat_code="901Y027",
                cycle=Cycle.MONTHLY,
                item_code1="I61BC",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.employment_rate = Indicator(
            client,
            IndicatorSpec(
                path="employment.employment_rate",
                name_ko="고용률",
                name_en="Employment Rate",
                stat_code="901Y027",
                cycle=Cycle.MONTHLY,
                item_code1="I61E",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.active_population = Indicator(
            client,
            IndicatorSpec(
                path="employment.active_population",
                name_ko="경제활동인구",
                name_en="Economically Active Population",
                stat_code="901Y027",
                cycle=Cycle.MONTHLY,
                item_code1="I61B",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.employed_persons = Indicator(
            client,
            IndicatorSpec(
                path="employment.employed_persons",
                name_ko="취업자수",
                name_en="Employed Persons",
                stat_code="901Y027",
                cycle=Cycle.MONTHLY,
                item_code1="I61BA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.hourly_wage = Indicator(
            client,
            IndicatorSpec(
                path="employment.hourly_wage",
                name_ko="시간당명목임금지수",
                name_en="Hourly Nominal Wage Index",
                stat_code="901Y102",
                cycle=Cycle.QUARTERLY,
                item_code1="A10001",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.labor_productivity = Indicator(
            client,
            IndicatorSpec(
                path="employment.labor_productivity",
                name_ko="노동생산성지수",
                name_en="Index of Labor Productivity",
                stat_code="901Y107",
                cycle=Cycle.QUARTERLY,
                item_code1="A",
                item_code2="I70D",
                item_code3=None,
            ),
        )
        self.unit_labor_cost = Indicator(
            client,
            IndicatorSpec(
                path="employment.unit_labor_cost",
                name_ko="단위노동비용지수",
                name_en="Unit Labor Cost",
                stat_code="901Y088",
                cycle=Cycle.QUARTERLY,
                item_code1="E70A",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Population:
    """Curated indicators under ``population``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.projected = Indicator(
            client,
            IndicatorSpec(
                path="population.projected",
                name_ko="추계인구",
                name_en="Population Projected",
                stat_code="901Y028",
                cycle=Cycle.ANNUAL,
                item_code1="I35A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.elderly_ratio = Indicator(
            client,
            IndicatorSpec(
                path="population.elderly_ratio",
                name_ko="고령인구비율",
                name_en="Elderly Population Ratio",
                stat_code="901Y028",
                cycle=Cycle.ANNUAL,
                item_code1="I35D",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.fertility_rate = Indicator(
            client,
            IndicatorSpec(
                path="population.fertility_rate",
                name_ko="합계출산율",
                name_en="Total Fertility Rate",
                stat_code="901Y028",
                cycle=Cycle.ANNUAL,
                item_code1="I35E",
                item_code2=None,
                item_code3=None,
            ),
        )


class _ExternalReserves:
    """Curated indicators under ``external.reserves``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.total = Indicator(
            client,
            IndicatorSpec(
                path="external.reserves.total",
                name_ko="외환보유액",
                name_en="International Reserves",
                stat_code="732Y001",
                cycle=Cycle.MONTHLY,
                item_code1="99",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.fx = Indicator(
            client,
            IndicatorSpec(
                path="external.reserves.fx",
                name_ko="외환보유액(외환)",
                name_en="International Reserves: Foreign Exchange",
                stat_code="732Y001",
                cycle=Cycle.MONTHLY,
                item_code1="04",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.gold = Indicator(
            client,
            IndicatorSpec(
                path="external.reserves.gold",
                name_ko="외환보유액(금)",
                name_en="International Reserves: Gold",
                stat_code="732Y001",
                cycle=Cycle.MONTHLY,
                item_code1="01",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.sdr = Indicator(
            client,
            IndicatorSpec(
                path="external.reserves.sdr",
                name_ko="외환보유액(SDR)",
                name_en="International Reserves: SDRs",
                stat_code="732Y001",
                cycle=Cycle.MONTHLY,
                item_code1="02",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.imf = Indicator(
            client,
            IndicatorSpec(
                path="external.reserves.imf",
                name_ko="외환보유액(IMF포지션)",
                name_en="International Reserves: IMF Reserve Position",
                stat_code="732Y001",
                cycle=Cycle.MONTHLY,
                item_code1="03",
                item_code2=None,
                item_code3=None,
            ),
        )


class _External:
    """Curated indicators under ``external``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.current_account = Indicator(
            client,
            IndicatorSpec(
                path="external.current_account",
                name_ko="경상수지",
                name_en="Current Account",
                stat_code="301Y013",
                cycle=Cycle.MONTHLY,
                item_code1="000000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.direct_investment_assets = Indicator(
            client,
            IndicatorSpec(
                path="external.direct_investment_assets",
                name_ko="직접투자(자산)",
                name_en="Direct Investment, Assets",
                stat_code="301Y013",
                cycle=Cycle.MONTHLY,
                item_code1="BOPF11000000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.direct_investment_liabilities = Indicator(
            client,
            IndicatorSpec(
                path="external.direct_investment_liabilities",
                name_ko="직접투자(부채)",
                name_en="Direct Investment, Liabilities",
                stat_code="301Y013",
                cycle=Cycle.MONTHLY,
                item_code1="BOPF12000000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.portfolio_investment_assets = Indicator(
            client,
            IndicatorSpec(
                path="external.portfolio_investment_assets",
                name_ko="증권투자(자산)",
                name_en="Portfolio Investment, Assets",
                stat_code="301Y013",
                cycle=Cycle.MONTHLY,
                item_code1="BOPF21000000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.portfolio_investment_liabilities = Indicator(
            client,
            IndicatorSpec(
                path="external.portfolio_investment_liabilities",
                name_ko="증권투자(부채)",
                name_en="Portfolio Investment, Liabilities",
                stat_code="301Y013",
                cycle=Cycle.MONTHLY,
                item_code1="BOPF22000000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.reserves = _ExternalReserves(client)
        self.debt = Indicator(
            client,
            IndicatorSpec(
                path="external.debt",
                name_ko="대외채무",
                name_en="External Debt",
                stat_code="311Y004",
                cycle=Cycle.QUARTERLY,
                item_code1="A000000",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.claims = Indicator(
            client,
            IndicatorSpec(
                path="external.claims",
                name_ko="대외채권",
                name_en="External Claims",
                stat_code="311Y005",
                cycle=Cycle.QUARTERLY,
                item_code1="B000000",
                item_code2=None,
                item_code3=None,
            ),
        )


class _TradeExportsSemiconductor:
    """Curated indicators under ``trade.exports.semiconductor``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.value = Indicator(
            client,
            IndicatorSpec(
                path="trade.exports.semiconductor.value",
                name_ko="반도체 수출금액지수",
                name_en="Semiconductor Export Value Index",
                stat_code="403Y001",
                cycle=Cycle.MONTHLY,
                item_code1="30911AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.volume = Indicator(
            client,
            IndicatorSpec(
                path="trade.exports.semiconductor.volume",
                name_ko="반도체 수출물량지수",
                name_en="Semiconductor Export Volume Index",
                stat_code="403Y002",
                cycle=Cycle.MONTHLY,
                item_code1="30911AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.price = Indicator(
            client,
            IndicatorSpec(
                path="trade.exports.semiconductor.price",
                name_ko="반도체 수출물가지수",
                name_en="Semiconductor Export Price Index",
                stat_code="402Y014",
                cycle=Cycle.MONTHLY,
                item_code1="30911AA",
                item_code2=None,
                item_code3=None,
            ),
        )


class _TradeExports:
    """Curated indicators under ``trade.exports``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.value = Indicator(
            client,
            IndicatorSpec(
                path="trade.exports.value",
                name_ko="수출금액지수",
                name_en="Export value index",
                stat_code="403Y001",
                cycle=Cycle.MONTHLY,
                item_code1="*AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.volume = Indicator(
            client,
            IndicatorSpec(
                path="trade.exports.volume",
                name_ko="수출물량지수",
                name_en="Export volume index",
                stat_code="403Y002",
                cycle=Cycle.MONTHLY,
                item_code1="*AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.price = Indicator(
            client,
            IndicatorSpec(
                path="trade.exports.price",
                name_ko="수출물가지수",
                name_en="Export Price Index",
                stat_code="402Y014",
                cycle=Cycle.MONTHLY,
                item_code1="*AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.semiconductor = _TradeExportsSemiconductor(client)


class _TradeImportsSemiconductor:
    """Curated indicators under ``trade.imports.semiconductor``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.value = Indicator(
            client,
            IndicatorSpec(
                path="trade.imports.semiconductor.value",
                name_ko="반도체 수입금액지수",
                name_en="Semiconductor Import Value Index",
                stat_code="403Y003",
                cycle=Cycle.MONTHLY,
                item_code1="30911AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.volume = Indicator(
            client,
            IndicatorSpec(
                path="trade.imports.semiconductor.volume",
                name_ko="반도체 수입물량지수",
                name_en="Semiconductor Import Volume Index",
                stat_code="403Y004",
                cycle=Cycle.MONTHLY,
                item_code1="30911AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.price = Indicator(
            client,
            IndicatorSpec(
                path="trade.imports.semiconductor.price",
                name_ko="반도체 수입물가지수",
                name_en="Semiconductor Import Price Index",
                stat_code="401Y015",
                cycle=Cycle.MONTHLY,
                item_code1="30911AA",
                item_code2=None,
                item_code3=None,
            ),
        )


class _TradeImports:
    """Curated indicators under ``trade.imports``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.value = Indicator(
            client,
            IndicatorSpec(
                path="trade.imports.value",
                name_ko="수입금액지수",
                name_en="Import value index",
                stat_code="403Y003",
                cycle=Cycle.MONTHLY,
                item_code1="*AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.volume = Indicator(
            client,
            IndicatorSpec(
                path="trade.imports.volume",
                name_ko="수입물량지수",
                name_en="Import volume index",
                stat_code="403Y004",
                cycle=Cycle.MONTHLY,
                item_code1="*AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.price = Indicator(
            client,
            IndicatorSpec(
                path="trade.imports.price",
                name_ko="수입물가지수",
                name_en="Import Price Index",
                stat_code="401Y015",
                cycle=Cycle.MONTHLY,
                item_code1="*AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.semiconductor = _TradeImportsSemiconductor(client)


class _TradeTermsOfTrade:
    """Curated indicators under ``trade.terms_of_trade``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.net = Indicator(
            client,
            IndicatorSpec(
                path="trade.terms_of_trade.net",
                name_ko="순상품교역조건지수",
                name_en="Net Barter Terms of Trade Index",
                stat_code="403Y005",
                cycle=Cycle.MONTHLY,
                item_code1="A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.income = Indicator(
            client,
            IndicatorSpec(
                path="trade.terms_of_trade.income",
                name_ko="소득교역조건지수",
                name_en="Income Terms of Trade Index",
                stat_code="403Y005",
                cycle=Cycle.MONTHLY,
                item_code1="B",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Trade:
    """Curated indicators under ``trade``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.exports = _TradeExports(client)
        self.imports = _TradeImports(client)
        self.terms_of_trade = _TradeTermsOfTrade(client)


class _PriceProducer:
    """Curated indicators under ``price.producer``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.dram = Indicator(
            client,
            IndicatorSpec(
                path="price.producer.dram",
                name_ko="DRAM 생산자물가",
                name_en="DRAM Producer Price",
                stat_code="404Y016",
                cycle=Cycle.MONTHLY,
                item_code1="30911201AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.nand = Indicator(
            client,
            IndicatorSpec(
                path="price.producer.nand",
                name_ko="NAND플래시 생산자물가",
                name_en="NAND Flash Producer Price",
                stat_code="404Y016",
                cycle=Cycle.MONTHLY,
                item_code1="30911202AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.system_semiconductor = Indicator(
            client,
            IndicatorSpec(
                path="price.producer.system_semiconductor",
                name_ko="시스템반도체 생산자물가",
                name_en="System Semiconductor Producer Price",
                stat_code="404Y016",
                cycle=Cycle.MONTHLY,
                item_code1="30911203AA",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Price:
    """Curated indicators under ``price``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.cpi = Indicator(
            client,
            IndicatorSpec(
                path="price.cpi",
                name_ko="소비자물가지수",
                name_en="Consumer Price Index",
                stat_code="901Y009",
                cycle=Cycle.MONTHLY,
                item_code1="0",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.core_cpi = Indicator(
            client,
            IndicatorSpec(
                path="price.core_cpi",
                name_ko="농산물 및 석유류제외 소비자물가지수",
                name_en="CPI Excluding Agricultural Products & Oils",
                stat_code="901Y010",
                cycle=Cycle.MONTHLY,
                item_code1="QB",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.living_cpi = Indicator(
            client,
            IndicatorSpec(
                path="price.living_cpi",
                name_ko="생활물가지수",
                name_en="CPI For Living Necessaries",
                stat_code="901Y010",
                cycle=Cycle.MONTHLY,
                item_code1="110",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.ppi = Indicator(
            client,
            IndicatorSpec(
                path="price.ppi",
                name_ko="생산자물가지수",
                name_en="Producer Price Index",
                stat_code="404Y014",
                cycle=Cycle.MONTHLY,
                item_code1="*AA",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.producer = _PriceProducer(client)


class _RealEstate:
    """Curated indicators under ``real_estate``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.house_sales_price = Indicator(
            client,
            IndicatorSpec(
                path="real_estate.house_sales_price",
                name_ko="주택매매가격지수",
                name_en="Housing Sales Price Index",
                stat_code="901Y062",
                cycle=Cycle.MONTHLY,
                item_code1="P63A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.house_jeonse_price = Indicator(
            client,
            IndicatorSpec(
                path="real_estate.house_jeonse_price",
                name_ko="주택전세가격지수",
                name_en="Housing Jeonse Price Index",
                stat_code="901Y063",
                cycle=Cycle.MONTHLY,
                item_code1="P64A",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.land_price_change = Indicator(
            client,
            IndicatorSpec(
                path="real_estate.land_price_change",
                name_ko="지가변동률(전기대비)",
                name_en="Land Price Change Rates",
                stat_code="901Y064",
                cycle=Cycle.MONTHLY,
                item_code1="P65A",
                item_code2=None,
                item_code3=None,
            ),
        )


class _Commodity:
    """Curated indicators under ``commodity``."""

    def __init__(self, client: _SeriesClient) -> None:
        self.dubai_oil = Indicator(
            client,
            IndicatorSpec(
                path="commodity.dubai_oil",
                name_ko="Dubai유(현물)",
                name_en="Dubai Crude Oil",
                stat_code="902Y003",
                cycle=Cycle.MONTHLY,
                item_code1="010102",
                item_code2=None,
                item_code3=None,
            ),
        )
        self.gold = Indicator(
            client,
            IndicatorSpec(
                path="commodity.gold",
                name_ko="금",
                name_en="Gold Price(Spot)",
                stat_code="902Y003",
                cycle=Cycle.MONTHLY,
                item_code1="040101",
                item_code2=None,
                item_code3=None,
            ),
        )


class _CurationGroups:
    """Curated indicators, grouped, reached as ``ecos.<group>.<indicator>``.

    ``ECOS`` inherits this and sets :attr:`_series_client` to itself, so each
    group builds lazily on first access and stays bound to that client.
    """

    _series_client: _SeriesClient

    @cached_property
    def rate(self) -> _Rate:
        return _Rate(self._series_client)

    @cached_property
    def credit(self) -> _Credit:
        return _Credit(self._series_client)

    @cached_property
    def money(self) -> _Money:
        return _Money(self._series_client)

    @cached_property
    def fx(self) -> _Fx:
        return _Fx(self._series_client)

    @cached_property
    def stock(self) -> _Stock:
        return _Stock(self._series_client)

    @cached_property
    def bond(self) -> _Bond:
        return _Bond(self._series_client)

    @cached_property
    def growth(self) -> _Growth:
        return _Growth(self._series_client)

    @cached_property
    def production(self) -> _Production:
        return _Production(self._series_client)

    @cached_property
    def consumption(self) -> _Consumption:
        return _Consumption(self._series_client)

    @cached_property
    def investment(self) -> _Investment:
        return _Investment(self._series_client)

    @cached_property
    def business_cycle(self) -> _BusinessCycle:
        return _BusinessCycle(self._series_client)

    @cached_property
    def sentiment(self) -> _Sentiment:
        return _Sentiment(self._series_client)

    @cached_property
    def corporate(self) -> _Corporate:
        return _Corporate(self._series_client)

    @cached_property
    def household(self) -> _Household:
        return _Household(self._series_client)

    @cached_property
    def employment(self) -> _Employment:
        return _Employment(self._series_client)

    @cached_property
    def population(self) -> _Population:
        return _Population(self._series_client)

    @cached_property
    def external(self) -> _External:
        return _External(self._series_client)

    @cached_property
    def trade(self) -> _Trade:
        return _Trade(self._series_client)

    @cached_property
    def price(self) -> _Price:
        return _Price(self._series_client)

    @cached_property
    def real_estate(self) -> _RealEstate:
        return _RealEstate(self._series_client)

    @cached_property
    def commodity(self) -> _Commodity:
        return _Commodity(self._series_client)
